### ISSUE TITLE
Deprecated strlen() and strchr()

### ISSUE THREAD

**Issue by klaoun** [Piwigo/AStat#5]
hi
i have this error in admin.php?page=plugin-AStat-stats_by_image
Deprecated: strchr(): Passing null to parameter # 1 ($haystack) of type string is deprecated in /var/www/html/include/functions.inc.php on line 72

Deprecated: strlen(): Passing null to parameter # 1 ($string) of type string is deprecated in /var/www/html/include/functions.inc.php on line 72

piwigo 13.6.0
php 8.1+

**Comment by Windrider6** [comment]
I too see these errors on Astat.2: Settings: Per pictures

Deprecated: strrchr(): Passing null to parameter #1 ($haystack) of type string is deprecated in /home/windride/public_html/wallpaper/include/functions.inc.php on line 72

Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /home/windride/public_html/wallpaper/include/functions.inc.php on line 72

For me, there are 5 of these pairs on my first page.  Maybe they have something to do with the 5 items in my list: "Picture doesn't exist anymore [ Id #0 ]"

Or maybe they have something to do with the many items in my list that start off:
"Section : Unknown [categories] /"
